# This file was generated by GoReleaser. DO NOT EDIT.
cask "dwx" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "0cc238618d440a08f5c555ab3f671e5c23da63f96b92a93c5f7e557c42e60307"
      url "https://github.com/datawerx/datawerx-mesh/releases/download/v#{version}/datawerx_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0d031af50d8c6d37ad5042047c7361717b35e08233dd5d8bf5a5c04db63929e7"
      url "https://github.com/datawerx/datawerx-mesh/releases/download/v#{version}/datawerx_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "64d751b76efc2af668fe640f06e7a43ab91ab1126f6f4369b3527d666b8d9b36"
      url "https://github.com/datawerx/datawerx-mesh/releases/download/v#{version}/datawerx_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6e213b0a4b43ad3fd6d6e6bc482db9a6ed887222a36d93efc275cd18aa6c1932"
      url "https://github.com/datawerx/datawerx-mesh/releases/download/v#{version}/datawerx_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dwx"
  desc "DataWerx unified CLI (dwx), with the deprecated dwxctl and dwx-mcp aliases"
  homepage "https://github.com/DataWerx/datawerx-mesh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dwx"
  binary "dwxctl"
  binary "dwx-mcp"

  # No zap stanza required

end
