# This file was generated by GoReleaser. DO NOT EDIT.
cask "dwx" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "297612d4e6a08d53e91b8c14f534157c65b1a0853c8112e1c952e1a02bda62bb"
      url "https://github.com/datawerx/datawerx-mesh/releases/download/v#{version}/datawerx_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "19295ef5b7964d1ea9320f0ac1559e856857a662dd11f3cc19113d7509318d9e"
      url "https://github.com/datawerx/datawerx-mesh/releases/download/v#{version}/datawerx_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6c70529a142860c6c827920615218fed938ada1dd2c362221939a922f5eefe1d"
      url "https://github.com/datawerx/datawerx-mesh/releases/download/v#{version}/datawerx_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0d0fb7a0f81737a61dd1f38f717ae550f41a8de1d7793af9d9fb688c686681b1"
      url "https://github.com/datawerx/datawerx-mesh/releases/download/v#{version}/datawerx_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dwx"
  desc "DataWerx unified CLI (dwx), with the deprecated dwxctl and dwx-mcp aliases"
  homepage "https://github.com/DataWerx/datawerx-mesh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dwx"
  binary "dwxctl"
  binary "dwx-mcp"

  # No zap stanza required

end
