# This file was generated by GoReleaser. DO NOT EDIT.
cask "dwxctl" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "71b54efa03546a130a1de83306b5df467bc67588f80e019b36ff13ffe78c3608"
      url "https://github.com/datawerx/datawerx-mesh/releases/download/v#{version}/datawerx_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "28243e7d758a314a03f802c7d2196d8eac30bf6ffd1d10391b632cd99aec6a4e"
      url "https://github.com/datawerx/datawerx-mesh/releases/download/v#{version}/datawerx_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "be534d1179dd0ae5732a9cbbd23670126647e2872bec8563ef3056e90841e760"
      url "https://github.com/datawerx/datawerx-mesh/releases/download/v#{version}/datawerx_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a67e794fd25e6863ea0eb1dddedfe36a98ee6aaf377f83472b2ca037c78c2db9"
      url "https://github.com/datawerx/datawerx-mesh/releases/download/v#{version}/datawerx_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dwxctl"
  desc "DataWerx Mesh operator CLI (dwxctl) and read-only MCP server (dwx-mcp)"
  homepage "https://github.com/DataWerx/datawerx-mesh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dwxctl"
  binary "dwx-mcp"

  # No zap stanza required

end
